### GET ALL WORKERS
GET http://localhost:8080/api/v1/workers

###

### GET ONE WORKER
GET http://localhost:8080/api/v1/workers/67d738bc4560785d1cdc1a49

###

### DELETE ONE WORKER
DELETE http://localhost:8080/api/v1/workers/67d855427608991df9dddf2a

###

### CREATE ONE WORKER
# @no-cookie-jar
POST http://localhost:8080/api/v1/workers
Content-Type: application/json

{
  "name": "John Doe",
  "position": "Software Engineer",
  "salary": 75000.0
}

###

### UPDATE ONE WORKER
PUT http://localhost:8080/api/v1/workers
Content-Type: application/json

{
  "id": "2",
  "name": "Jane Smith",
  "position": "Senior Software Engineer",
  "salary": 90000.0
}
